
version: 2

models:
  - name: meanticketpercustomer
    description: "valor médio unitário por cliente"
    columns:
      - name: '"CustomerID"'
        tests:
          - not_null
          - unique

      - name: mean_unitprice
        description: "Preço médio por cliente"
        tests:
          - not_null

